#!/bin/bash

SERVICE_NAME="eye-of-abyss-prokid.service"

echo "* Restarting $SERVICE_NAME *"
sudo systemctl restart "$SERVICE_NAME"

sleep 1
echo "* Tailing logs for $SERVICE_NAME (ctrl+c to exit) *"
sleep 1
journalctl -fu "$SERVICE_NAME"


# cd ~/eye-of-abyss
# sudo bash scripts/start
# sudo bash scripts/start_all